// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4s2ridb5gcsYiqKsO0B6jA4SHjzfPL6g',
    appId: '1:318867737038:web:642d0be618af121c04439f',
    messagingSenderId: '318867737038',
    projectId: 'guideye-b8330',
    authDomain: 'guideye-b8330.firebaseapp.com',
    databaseURL: 'https://guideye-b8330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guideye-b8330.appspot.com',
    measurementId: 'G-6HXKE221VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTh1ic9DrC3rIDwhaufS13swtMxC0adyM',
    appId: '1:318867737038:android:6b02c13caea582cc04439f',
    messagingSenderId: '318867737038',
    projectId: 'guideye-b8330',
    databaseURL: 'https://guideye-b8330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guideye-b8330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtiM07KNbrwJssCgPezQD5GzQtBWpwJs',
    appId: '1:318867737038:ios:bdf23fc5fcb95c9604439f',
    messagingSenderId: '318867737038',
    projectId: 'guideye-b8330',
    databaseURL: 'https://guideye-b8330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guideye-b8330.appspot.com',
    androidClientId: '318867737038-idthjj0a84pm968scjk99cgrtsalji4d.apps.googleusercontent.com',
    iosClientId: '318867737038-et8rgapde3lf7stir0brhvj638a416pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.guideyeWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtiM07KNbrwJssCgPezQD5GzQtBWpwJs',
    appId: '1:318867737038:ios:bdf23fc5fcb95c9604439f',
    messagingSenderId: '318867737038',
    projectId: 'guideye-b8330',
    databaseURL: 'https://guideye-b8330-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guideye-b8330.appspot.com',
    androidClientId: '318867737038-idthjj0a84pm968scjk99cgrtsalji4d.apps.googleusercontent.com',
    iosClientId: '318867737038-et8rgapde3lf7stir0brhvj638a416pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.guideyeWebsite',
  );
}
